FROM opensearchproject/opensearch:latest
ENV discovery.type=single-node
ENV OPENSEARCH_JAVA_OPTS=-Xmx1G -Xms1G
ENV DISABLE_SECURITY=${DISABLE_SECURITY:-true}
ENV OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD:-}
